### PR TITLE
Simpler URL handling and support for bookmarking

### PR DESCRIPTION
**Pull request by clente**
Now the user doesn't have to specify local/remote_url and bookmarking via server is supported.

### CODE REVIEW

**Comment by daattali** [comment]
Removing local/remote url config is great!

What's the problem for supporting url-based bookmarking? Is it because of this bug https://github.com/rstudio/shiny/issues/2297 ?

I think I mentioned this before, but if you have control over the URL parameter names (`code` and `state` specifically), I would suggest using more unique names

**Comment by clente** [comment]
I think the problem is with Auth0's way of handling URLs: instead of redirecting the user to, e.g., `url/?_inputs_&n=200` it redirects to `url/?_inputs_=&n=200`... That extra equals sign breaks bookmarking.

As far as we were able to research, it seems like you can't control `code` and `state`.

**Comment by daattali** [comment]
That's a shame that shiny uses a non standard way to encode the params. Although it feels like a bug in auth0's side to me, that they don't redirect to exactly the same URL and they mess around with it. Do you agree that it sounds like a bug in auth0? If so, do you know which repository [in auth0's account](https://github.com/auth0) should be responsible for this so we can open an issue?

Otherwise, until this is fixed, I understand URL bookmarking won't work.

**Comment by clente** [comment]
I've created an issue on Auth0's side too: https://github.com/auth0/auth0.js/issues/1038

For now, that's all we can do :(

**Pull request merged**
